"""Local Python executor using a subprocess.

Runs Python code in a fresh interpreter under a wall-clock timeout, with
optional CPU/memory rlimits on Linux/macOS. The cwd is a fresh temp dir per
call. Captured stdout, stderr, and return code are emitted as
``COMPUTATION`` evidence.

**Trust boundary.** This is NOT a hardened sandbox. It is *good enough* for
the harness's intended use — running deterministic, harness-authored code
(e.g. generated by an LLM-backed translator that must still pass downstream
verification). For untrusted user-supplied code, swap this implementation
for an E2B/Modal/Daytona adapter behind the same ``Tool`` interface; the
shape of evidence the harness expects does not change.

Expected context shape::

    request.context["code"] = "<python source>"
    # Optional:
    request.context["timeout_s"] = 5.0
    request.context["cpu_seconds"] = 5
    request.context["memory_mb"] = 256

If ``code`` is absent, the executor attempts to extract a triple-backtick
``python`` block from the claim text.
"""

from __future__ import annotations

import os
import platform
import re
import subprocess
import sys
import tempfile
from typing import Any

from ...domain.evidence import (
    FreshnessStatus,
    SourceQuality,
    SourceType,
    SupportStatus,
)
from .base import Tool, ToolRequest, ToolResult, build_evidence


_FENCED_PY = re.compile(r"```(?:python|py)?\s*(.+?)```", re.DOTALL | re.IGNORECASE)


def _extract_code_from_claim(text: str) -> str | None:
    m = _FENCED_PY.search(text)
    if m:
        return m.group(1).strip() or None
    return None


def _can_set_rlimits() -> bool:
    return platform.system() != "Windows"


def _make_preexec(cpu_seconds: int | None, memory_mb: int | None):
    """Return a preexec_fn that applies rlimits, or ``None`` when unsupported."""
    if not _can_set_rlimits() or (cpu_seconds is None and memory_mb is None):
        return None
    import resource  # POSIX-only

    def _preexec() -> None:
        if cpu_seconds is not None:
            resource.setrlimit(resource.RLIMIT_CPU, (cpu_seconds, cpu_seconds))
        if memory_mb is not None:
            try:
                limit = memory_mb * 1024 * 1024
                resource.setrlimit(resource.RLIMIT_AS, (limit, limit))
            except (ValueError, OSError):
                # Some platforms (notably macOS) don't honor RLIMIT_AS.
                pass

    return _preexec


class LocalSubprocessPythonExecutor:
    name = "python_executor"

    def __init__(
        self,
        *,
        default_timeout_s: float = 5.0,
        default_cpu_seconds: int | None = 5,
        default_memory_mb: int | None = 256,
    ) -> None:
        self._timeout_s = default_timeout_s
        self._cpu_seconds = default_cpu_seconds
        self._memory_mb = default_memory_mb

    def run(self, request: ToolRequest) -> ToolResult:
        ctx: dict[str, Any] = request.context
        code = ctx.get("code")
        if not isinstance(code, str) or not code.strip():
            code = _extract_code_from_claim(request.claim.text)
        if not code:
            return ToolResult(
                succeeded=False,
                error="Python executor requires context['code'] or fenced ```python``` in the claim.",
            )

        timeout_s = float(ctx.get("timeout_s", self._timeout_s))
        cpu_seconds = ctx.get("cpu_seconds", self._cpu_seconds)
        memory_mb = ctx.get("memory_mb", self._memory_mb)

        with tempfile.TemporaryDirectory() as tmpdir:
            script_path = os.path.join(tmpdir, "snippet.py")
            with open(script_path, "w", encoding="utf-8") as f:
                f.write(code)

            try:
                proc = subprocess.run(
                    [sys.executable, "-I", "-S", script_path],
                    cwd=tmpdir,
                    capture_output=True,
                    text=True,
                    timeout=timeout_s,
                    preexec_fn=_make_preexec(cpu_seconds, memory_mb),
                    check=False,
                )
            except subprocess.TimeoutExpired:
                return ToolResult(
                    succeeded=False,
                    error=f"Python execution timed out after {timeout_s} seconds.",
                )
            except OSError as e:
                return ToolResult(succeeded=False, error=f"Failed to launch interpreter: {e}")

        succeeded = proc.returncode == 0
        stdout = proc.stdout or ""
        stderr = proc.stderr or ""
        # Truncate captured output to keep evidence records bounded.
        stdout_snippet = stdout[-4000:]
        stderr_snippet = stderr[-1000:]

        return ToolResult(
            succeeded=succeeded,
            evidence=[
                build_evidence(
                    claim_id=request.claim.id,
                    source_type=SourceType.COMPUTATION,
                    source_name="python_subprocess",
                    quote_or_result=(
                        f"return_code={proc.returncode}\n"
                        f"--- stdout ---\n{stdout_snippet}"
                        + (f"\n--- stderr ---\n{stderr_snippet}" if stderr_snippet else "")
                    ),
                    normalized_result={
                        "return_code": proc.returncode,
                        "stdout": stdout_snippet,
                        "stderr": stderr_snippet,
                        "timeout_s": timeout_s,
                    },
                    supports_claim=(
                        SupportStatus.SUPPORTS if succeeded else SupportStatus.INSUFFICIENT
                    ),
                    source_quality=(
                        SourceQuality.AUTHORITATIVE if succeeded else SourceQuality.UNKNOWN
                    ),
                    freshness=FreshnessStatus.NOT_TIME_SENSITIVE,
                    notes=(
                        "Local subprocess executor — NOT a hardened sandbox. "
                        "Swap for E2B/Modal for untrusted code."
                    ),
                )
            ],
            error=None if succeeded else f"Process exited with {proc.returncode}.",
        )


_: Tool = LocalSubprocessPythonExecutor()
